services:
  backend:
    build: ./backend
    container_name: freetube-backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: freetube-frontend
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend

  db:
    image: postgres:latest
    container_name: freetube-postgres
    environment:
      POSTGRES_USER: freetube
      POSTGRES_PASSWORD: freetube123
      POSTGRES_DB: freetube
    ports:
      - "5433:5432"  
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
